language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt

addons:
  sonarcloud: Gtrue

script:
  -sonar-scanner -D sonar.host.url=https://sonarcloud.io -D sonar.organization=julyluna10 -D sonar.login=$SONAR_TOKEN -X
  -pytest

notifications:
   slack: tpi-grupo:KU9ouAhc1AnsAkBca3h2F7A1


