language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt

addons:
  sonarcloud: true

script:
  - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=julyluna10
  -Dsonar.login=$SONAR_TOKEN -X
  - pytest

#addons:
 # sonarcloud:
  #  organization: "julyluna10"
  #  token:
     # secure: $SONAR_TOKEN
      #"**************************" # encrypted value of your token

#script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
 # - sonar-scanner
 # - pytest

notifications:
   slack: tpi-grupo:KU9ouAhc1AnsAkBca3h2F7A1

#deploy:
  #provider: heroku
 # skip_cleanup: true
 # keep-history: true
 # api_key: de63704f-cde6-4771-98d4-1523e8e998ad
 # app: calculadora-py
  #on:
   # repo: julyluna10/CalculadoraPY

