language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
addons:
  sonarcloud: true

script:
  - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ericaudizzio -Dsonar.login=$SONAR_TOKEN -X
  - pytest

notifications:
   slack: tpi-grupo:KU9ouAhc1AnsAkBca3h2F7A1
